kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.service }}
  labels:
    app: {{ .Values.service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.service }}
        image: {{ .Values.awsAccountId }}.dkr.ecr.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.service }}:{{ $.Values.imagesVersion }}
        imagePullPolicy: Always
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: ship-secrets
                key: MONGO_URI
          - name: MONGO_DB_NAME
            valueFrom:
              secretKeyRef:
                name: ship-secrets
                key: MONGO_DB_NAME
          - name: API_URL
            valueFrom:
              secretKeyRef:
                name: ship-secrets
                key: API_URL
          - name: WEB_URL
            valueFrom:
              secretKeyRef:
                name: ship-secrets
                key: WEB_URL
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 100
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ .Values.nodeGroup }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
