kind: Job
apiVersion: batch/v1
metadata:
  name: {{ printf "%s-%s"  migrator (randAlpha 8) | lower | quote }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrator
          image: {{ .Values.migratorImage }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: api-{{ .Values.environment }}-secret
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ .Values.nodeGroup }}
  backoffLimit: 0
  activeDeadlineSeconds: 1800 # 30-minute max time for a migrator to complete the job
  ttlSecondsAfterFinished: 3600 # 1h to check pod logs after migrations finished
