services:
  redis:
    container_name: ship-redis
    image: redis:8.0.2
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - ship
    ports:
      - 6379:6379
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - ship
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/mailer/emails:/app/packages/mailer/emails
      - ./packages/mailer/src:/app/packages/mailer/src
    ports:
      - 3001:3001
    depends_on:
      - redis
  migrator:
    container_name: ship-migrator
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.migrator
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - ship
    volumes:
      - ./apps/api/src:/app/apps/api/src
  scheduler:
    container_name: ship-scheduler
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.scheduler
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - ship
    volumes:
      - ./apps/api/src:/app/apps/api/src
  web:
    container_name: ship-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
    networks:
      - ship
    ports:
      - 3002:3002
networks:
  ship:
    name: ship-network
