kind: Deployment
apiVersion: apps/v1
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      restartPolicy: Always
      envFrom:
        - configMapRef:
            name: api-{{ .Values.environment }}-configmap
        - secretRef:
            name: api-{{ .Values.environment }}-secret
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Values.service }}
          image: {{ .Values.containerRegistry }}-{{ .Values.service }}:{{ .Values.imagesVersion }}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      nodeSelector:
        doks.digitalocean.com/node-pool: {{ .Values.nodePool }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
