kind: Job
apiVersion: batch/v1
metadata:
  name: {{ printf "%s-%s"  .Chart.Name (randAlpha 8) | lower | quote }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.service }}
          image: {{ .Values.imagesVersion }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-{{ .Values.environment }}-configmap
            - secretRef:
                name: api-{{ .Values.environment }}-secret
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ .Values.nodeGroup }}
  backoffLimit: 0
  activeDeadlineSeconds: 1800 # 30 minutes max time for migrator to complete the job
  ttlSecondsAfterFinished: 3600 # 1h to check pod logs after migrations finished
