kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: {{ .Values.awsAccountId }}.dkr.ecr.{{ .Values.awsRegion }}.amazonaws.com/web:{{ $.Values.imagesVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
          protocol: TCP
      nodeSelector:
        eks.amazonaws.com/nodegroup: pool-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
