// flow-typed signature: b686ee613d4e1c53c90e50e8206f5e5f
// flow-typed version: <<STUB>>/joi-browser_v13.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'joi-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'joi-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'joi-browser/dist/joi-browser' {
  declare module.exports: any;
}

declare module 'joi-browser/dist/joi-browser.min' {
  declare module.exports: any;
}

declare module 'joi-browser/karma.conf' {
  declare module.exports: any;
}

declare module 'joi-browser/src/basic.kmocha' {
  declare module.exports: any;
}

declare module 'joi-browser/src/joi-browser' {
  declare module.exports: any;
}

declare module 'joi-browser/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'joi-browser/dist/joi-browser.js' {
  declare module.exports: $Exports<'joi-browser/dist/joi-browser'>;
}
declare module 'joi-browser/dist/joi-browser.min.js' {
  declare module.exports: $Exports<'joi-browser/dist/joi-browser.min'>;
}
declare module 'joi-browser/karma.conf.js' {
  declare module.exports: $Exports<'joi-browser/karma.conf'>;
}
declare module 'joi-browser/src/basic.kmocha.js' {
  declare module.exports: $Exports<'joi-browser/src/basic.kmocha'>;
}
declare module 'joi-browser/src/joi-browser.js' {
  declare module.exports: $Exports<'joi-browser/src/joi-browser'>;
}
declare module 'joi-browser/webpack.config.js' {
  declare module.exports: $Exports<'joi-browser/webpack.config'>;
}
