// flow-typed signature: 28df58d557215683cc96e09eb2c5ab3a
// flow-typed version: <<STUB>>/react-icon-base_v2.1.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icon-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icon-base' {
  declare export type IconBaseProps = {
    size?: string | number,
  };

  declare export default class IconBaseClass mixins React$Component<IconBaseProps>{}
}
