// flow-typed signature: 4e29e42ad60593a2c818235a4a78f763
// flow-typed version: <<STUB>>/react-router-redux_v5.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-redux/actions' {
  declare module.exports: any;
}

declare module 'react-router-redux/ConnectedRouter' {
  declare module.exports: any;
}

declare module 'react-router-redux/middleware' {
  declare module.exports: any;
}

declare module 'react-router-redux/reducer' {
  declare module.exports: any;
}

declare module 'react-router-redux/selectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-redux/actions.js' {
  declare module.exports: $Exports<'react-router-redux/actions'>;
}
declare module 'react-router-redux/ConnectedRouter.js' {
  declare module.exports: $Exports<'react-router-redux/ConnectedRouter'>;
}
declare module 'react-router-redux/index' {
  declare module.exports: $Exports<'react-router-redux'>;
}
declare module 'react-router-redux/index.js' {
  declare module.exports: $Exports<'react-router-redux'>;
}
declare module 'react-router-redux/middleware.js' {
  declare module.exports: $Exports<'react-router-redux/middleware'>;
}
declare module 'react-router-redux/reducer.js' {
  declare module.exports: $Exports<'react-router-redux/reducer'>;
}
declare module 'react-router-redux/selectors.js' {
  declare module.exports: $Exports<'react-router-redux/selectors'>;
}
