// flow-typed signature: 676f950ac84351a9c73f33a6bb85f4ae
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

import { Middleware, Dispatch } from 'redux';

declare module 'redux-thunk' {
  declare export type ThunkAction<R, S, E> = (
    dispatch: Dispatch<S>,
    getState: () => S,
    extraArgument: E
  ) => R;
  declare var thunk: Middleware & {
    withExtraArgument(extraArgument: any): Middleware
  };
  declare module.exports: typeof thunk;
}
