// flow-typed signature: 676f950ac84351a9c73f33a6bb85f4ae
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-thunk/lib/index' {
  declare module.exports: any;
}

declare module 'redux-thunk/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-thunk/lib/index.js' {
  declare module.exports: $Exports<'redux-thunk/lib/index'>;
}
declare module 'redux-thunk/src/index.js' {
  declare module.exports: $Exports<'redux-thunk/src/index'>;
}
