// flow-typed signature: 773af70fbccbc8c7c49cfd33d298f425
// flow-typed version: <<STUB>>/webpack_v3.11.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}

declare var module : {
  hot : {
    accept(path:string, callback:() => void): void;
  };
};

declare var require: any;

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack/hot/dev-server' {
  declare module.exports: any;
}

declare module 'webpack/hot/emitter' {
  declare module.exports: any;
}

declare module 'webpack/hot/log-apply-result' {
  declare module.exports: any;
}

declare module 'webpack/hot/log' {
  declare module.exports: any;
}

declare module 'webpack/hot/only-dev-server' {
  declare module.exports: any;
}

declare module 'webpack/hot/poll' {
  declare module.exports: any;
}

declare module 'webpack/hot/signal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack/hot/dev-server.js' {
  declare module.exports: $Exports<'webpack/hot/dev-server'>;
}
declare module 'webpack/hot/emitter.js' {
  declare module.exports: $Exports<'webpack/hot/emitter'>;
}
declare module 'webpack/hot/log-apply-result.js' {
  declare module.exports: $Exports<'webpack/hot/log-apply-result'>;
}
declare module 'webpack/hot/log.js' {
  declare module.exports: $Exports<'webpack/hot/log'>;
}
declare module 'webpack/hot/only-dev-server.js' {
  declare module.exports: $Exports<'webpack/hot/only-dev-server'>;
}
declare module 'webpack/hot/poll.js' {
  declare module.exports: $Exports<'webpack/hot/poll'>;
}
declare module 'webpack/hot/signal.js' {
  declare module.exports: $Exports<'webpack/hot/signal'>;
}
