import { existsSync, readdirSync, readFileSync, rmSync, statSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const ROUTER_PATH = join(SRC_DIR, 'router.ts');
const CONTRACT_PATH = join(SRC_DIR, 'contract.ts');
const HEADER = '// Auto-generated by codegen-router.ts — do not edit manually\n';

// eslint-disable-next-line ts/no-explicit-any
function isDir(entry: any): boolean {
  return entry.isDirectory() || (entry.isSymbolicLink() && statSync(join(RESOURCES_DIR, entry.name)).isDirectory());
}

function getResources(): string[] {
  if (!existsSync(RESOURCES_DIR)) return [];
  return readdirSync(RESOURCES_DIR, { withFileTypes: true })
    .filter((d) => isDir(d) && existsSync(join(RESOURCES_DIR, d.name, 'endpoints')))
    .map((d) => d.name)
    .sort();
}

function getEndpoints(resource: string): string[] {
  const dir = join(RESOURCES_DIR, resource, 'endpoints');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
    .map((f) => basename(f, '.ts'))
    .sort();
}

function getHandlers(resource: string): string[] {
  const dir = join(RESOURCES_DIR, resource, 'handlers');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => basename(f, '.ts'))
    .sort();
}

function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function buildRouter(resources: string[]): string {
  const handlerImports: string[] = [];
  const imports: string[] = [];
  const routerEntries: string[] = [];

  for (const r of resources) {
    for (const h of getHandlers(r)) {
      handlerImports.push(`import './resources/${r}/handlers/${h}';`);
    }

    const endpoints = getEndpoints(r);
    for (const p of endpoints) {
      const id = toCamelCase(`${r}_${p}`);
      imports.push(`import ${id} from './resources/${r}/endpoints/${p}';`);
    }
    const fields = endpoints.map((p) => `    ${toCamelCase(p)}: ${toCamelCase(`${r}_${p}`)},`);
    const key = r.includes('-') ? `'${r}'` : r;
    routerEntries.push(`  ${key}: isPublic.router({\n${fields.join('\n')}\n  }),`);
  }

  return [
    HEADER,
    ...handlerImports,
    ...(handlerImports.length ? [''] : []),
    "import type { RouterClient } from '@orpc/server';",
    '',
    ...imports,
    "import { isPublic } from './procedures';",
    '',
    'export const router = isPublic.router({',
    ...routerEntries,
    '});',
    '',
    'export type Router = typeof router;',
    'export type AppClient = RouterClient<Router>;',
    '',
  ].join('\n');
}

function cleanBarrels(resources: string[]): void {
  for (const r of resources) {
    const barrel = join(RESOURCES_DIR, r, 'endpoints', 'index.ts');
    if (existsSync(barrel)) rmSync(barrel);
  }
}

interface RouteInfo {
  method: string;
  path: string;
  successStatus?: number;
  outputStructure?: string;
}

function parseRouteInfo(resource: string, endpoint: string): RouteInfo | null {
  const filePath = join(RESOURCES_DIR, resource, 'endpoints', `${endpoint}.ts`);
  const content = readFileSync(filePath, 'utf-8');

  const routeMatch = content.match(/\.route\(\s*\{([\s\S]*?)\}\s*\)/);
  if (!routeMatch) return null;

  const body = routeMatch[1];
  const methodMatch = body.match(/method:\s*['"](\w+)['"]/);
  const pathMatch = body.match(/path:\s*['"]([^'"]+)['"]/);

  if (!methodMatch || !pathMatch) return null;

  const result: RouteInfo = { method: methodMatch[1], path: pathMatch[1] };

  const statusMatch = body.match(/successStatus:\s*(\d+)/);
  if (statusMatch) result.successStatus = Number.parseInt(statusMatch[1]);

  const structureMatch = body.match(/outputStructure:\s*['"](\w+)['"]/);
  if (structureMatch) result.outputStructure = structureMatch[1];

  return result;
}

function buildContract(resources: string[]): string {
  const contractEntries: string[] = [];

  for (const r of resources) {
    const endpoints = getEndpoints(r);
    const fields: string[] = [];

    for (const p of endpoints) {
      const name = toCamelCase(p);
      const route = parseRouteInfo(r, p);

      if (route) {
        const props = [`method: '${route.method}'`, `path: '${route.path}'`];
        if (route.successStatus) props.push(`successStatus: ${route.successStatus}`);
        if (route.outputStructure) props.push(`outputStructure: '${route.outputStructure}'`);
        fields.push(`    ${name}: oc.route({ ${props.join(', ')} }),`);
      } else {
        fields.push(`    ${name}: oc,`);
      }
    }

    contractEntries.push(`  ${r}: oc.router({\n${fields.join('\n')}\n  }),`);
  }

  return [
    HEADER,
    "import { oc } from '@orpc/contract';",
    '',
    'export const contract = oc.router({',
    ...contractEntries,
    '});',
    '',
  ].join('\n');
}

function run(): void {
  const resources = getResources();
  cleanBarrels(resources);

  const content = buildRouter(resources);
  const existing = existsSync(ROUTER_PATH) ? readFileSync(ROUTER_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(ROUTER_PATH, content);
    const total = resources.reduce((sum, r) => sum + getEndpoints(r).length, 0);
    // eslint-disable-next-line no-console
    console.log(`codegen-router: ${resources.length} resources, ${total} endpoints`);
  }

  const contractContent = buildContract(resources);
  const existingContract = existsSync(CONTRACT_PATH) ? readFileSync(CONTRACT_PATH, 'utf-8') : '';

  if (contractContent !== existingContract) {
    writeFileSync(CONTRACT_PATH, contractContent);
  }
}

run();

if (process.argv.includes('--watch')) {
  if (existsSync(RESOURCES_DIR)) {
    let timeout: ReturnType<typeof setTimeout> | null = null;
    watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
      if (!filename?.endsWith('.ts')) return;
      if (timeout) clearTimeout(timeout);
      timeout = setTimeout(run, 100);
    });
  }
}
