kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.service }}
  labels:
    app: {{ .Values.service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.service }}
        image: {{ .Values.imagesVersion }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: api-{{ .Values.environment }}-configmap
          - secretRef:
              name: api-{{ .Values.environment }}-secret
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ .Values.nodeGroup }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
