kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.service }}
  labels:
    app: {{ .Values.service }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service }}
                port:
                  number: {{ .Values.port }}
