// Auto-generated by codegen-db.ts — do not edit manually

import _db, { DbService, registerDb } from '@ship/db';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

import config from '@/config';
import { eventBus } from '@/event-bus';
import { accounts } from '@/resources/accounts/accounts.schema';
import { inviteTokens } from '@/resources/invite-tokens/invite-tokens.schema';
import { sessions } from '@/resources/sessions/sessions.schema';
import { users } from '@/resources/users/users.schema';
import { verifications } from '@/resources/verifications/verifications.schema';

const client = postgres(config.DATABASE_URL);

export const rawDb = drizzle({
  client,
  casing: 'snake_case',
  schema: {
    accounts,
    inviteTokens,
    sessions,
    users,
    verifications,
  },
});

const createDB = (db: typeof rawDb) => ({
  accounts: new DbService(accounts, db),
  inviteTokens: new DbService(inviteTokens, db),
  sessions: new DbService(sessions, db),
  users: new DbService(users, db, eventBus.hook('users')),
  verifications: new DbService(verifications, db),
  transaction: getTransactionalDB,
});

type TransactionCallback<T> = (db: DBType) => Promise<T>;

function getTransactionalDB<T>(callback: TransactionCallback<T>): Promise<T> {
  return rawDb.transaction(async (tx) => {
    // eslint-disable-next-line ts/no-explicit-any
    return await callback(createDB(tx as any));
  });
}

registerDb(createDB(rawDb), rawDb);

interface DBType {
  accounts: DbService<typeof accounts>;
  inviteTokens: DbService<typeof inviteTokens>;
  sessions: DbService<typeof sessions>;
  users: DbService<typeof users>;
  verifications: DbService<typeof verifications>;
  transaction: <T>(callback: TransactionCallback<T>) => Promise<T>;
}

// eslint-disable-next-line ts/no-explicit-any
export default _db as any as DBType;

export type Account = typeof accounts.$inferSelect;
export type InviteToken = typeof inviteTokens.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type User = typeof users.$inferSelect;
export type Verification = typeof verifications.$inferSelect;
