// Auto-generated by codegen-db.ts — do not edit manually

import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

import config from '@/config';
import { DbService, registerDb } from '@ship/db';
import { accounts } from '@/resources/accounts/accounts.schema';
import { sessions } from '@/resources/sessions/sessions.schema';
import { users } from '@/resources/users/users.schema';
import { verifications } from '@/resources/verifications/verifications.schema';

const client = postgres(config.DATABASE_URL);

const rawDb = drizzle({ client, schema: { accounts, sessions, users, verifications } });

registerDb({
  accounts: new DbService(accounts, rawDb),
  sessions: new DbService(sessions, rawDb),
  users: new DbService(users, rawDb),
  verifications: new DbService(verifications, rawDb),
}, rawDb);

export { default } from '@ship/db';

export type Account = typeof accounts.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type User = typeof users.$inferSelect;
export type Verification = typeof verifications.$inferSelect;
