import { Database, IDocument, Service, ServiceOptions } from '@paralect/node-mongo';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import config from 'config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const database = new Database(config.MONGO_URI, config.MONGO_DB_NAME);
database.connect();

class CustomService<T extends IDocument> extends Service<T> {
  // You can add new methods or override existing here
}

function createService<T extends IDocument>(collectionName: string, options: ServiceOptions = {}): Service<T> {
  return new CustomService<T>(collectionName, database, options);
}

export const services: Record<string, Service<IDocument>> = {};

interface SchemaEntry {
  name: string;
  resourceDir: string;
}

function generateDbTypes(schemas: SchemaEntry[]) {
  const imports = schemas.map(
    (s) => `import type ${s.name}Schema from 'resources/${s.resourceDir}/${s.name}.schema';`,
  );

  const serviceExports = schemas.map(
    (s) => `export const ${s.name}Service = services.${s.name} as Service<z.infer<typeof ${s.name}Schema>>;`,
  );

  const content = [
    '// Auto-generated by initDb — do not edit manually\n',
    "import type { z } from 'zod';",
    "import type { Service } from '@paralect/node-mongo';",
    ...imports,
    "import { services } from 'initDb';",
    '',
    ...serviceExports,
    '',
  ].join('\n');

  const filePath = path.join(__dirname, 'db.ts');
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';

  if (existing !== content) {
    fs.writeFileSync(filePath, content);
  }
}

export default async function init() {
  const resourcesDir = path.join(__dirname, 'resources');
  const entries = fs.readdirSync(resourcesDir, { withFileTypes: true });
  const schemas: SchemaEntry[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const dirPath = path.join(resourcesDir, entry.name);
    const files = fs.readdirSync(dirPath);
    const schemaFiles = files.filter((f) => f.endsWith('.schema.ts') || f.endsWith('.schema.js'));

    for (const schemaFile of schemaFiles) {
      const collectionName = schemaFile.replace(/\.schema\.(ts|js)$/, '');
      const mod = await import(path.join(dirPath, schemaFile));
      const schema = mod.default;

      const service = createService(collectionName, {
        schemaValidator: (obj) => schema.parseAsync(obj),
        ...(mod.secureFields && { secureFields: mod.secureFields }),
      });

      if (mod.indexes) {
        for (const idx of mod.indexes) {
          service.createIndex(idx.fields, idx.options);
        }
      }

      services[collectionName] = service;
      schemas.push({ name: collectionName, resourceDir: entry.name });
    }
  }

  generateDbTypes(schemas);
}

export { createService, database };
