// Auto-generated by codegen-router.ts — do not edit manually

import type { AppClient } from './router';

// eslint-disable-next-line ts/no-explicit-any
type AnyFn = (...args: any[]) => any;

type _BindInput<T extends AnyFn, K extends string> =
  T extends (input: infer I, ...rest: infer R) => infer O
    ? keyof Omit<I & {}, K> extends never
      ? (...rest: R) => O
      : (input: Omit<I & {}, K>, ...rest: R) => O
    : T;

export type FilesResource = AppClient['files'];

export type UsersResource = AppClient['users'];

export interface ResourceClient {
  files: FilesResource;
  users: UsersResource;
}
