// Auto-generated by codegen-router.ts — do not edit manually

import type { AppClient } from './router';

// eslint-disable-next-line ts/no-explicit-any
type AnyFn = (...args: any[]) => any;

type _BindInput<T extends AnyFn, K extends string> =
  T extends (input: infer I, ...rest: infer R) => infer O
    ? keyof Omit<I & {}, K> extends never
      ? (...rest: R) => O
      : (input: Omit<I & {}, K>, ...rest: R) => O
    : T;

export type FilesResource = AppClient['files'];

export type InviteTokensResource = AppClient['invite-tokens'];

export interface UsersResource {
  (params: { userId: string }): {
    delete: _BindInput<AppClient['users']['delete'], 'userId'>;
    update: _BindInput<AppClient['users']['update'], 'userId'>;
  };
  getCurrent: AppClient['users']['getCurrent'];
  patchCurrent: AppClient['users']['patchCurrent'];
  devVerifyEmail: AppClient['users']['devVerifyEmail'];
  list: AppClient['users']['list'];
}

export interface ResourceClient {
  files: FilesResource;
  'invite-tokens': InviteTokensResource;
  users: UsersResource;
}
