// Auto-generated by codegen-router.ts — do not edit manually

import type { RouterClient } from '@orpc/server';

import { pub } from './procedures';

import account_forgotPassword from './resources/account/procedures/forgotPassword';
import account_get from './resources/account/procedures/get';
import account_googleCallback from './resources/account/procedures/googleCallback';
import account_googleMobile from './resources/account/procedures/googleMobile';
import account_googleSignIn from './resources/account/procedures/googleSignIn';
import account_resendEmail from './resources/account/procedures/resendEmail';
import account_resetPassword from './resources/account/procedures/resetPassword';
import account_signIn from './resources/account/procedures/signIn';
import account_signOut from './resources/account/procedures/signOut';
import account_signUp from './resources/account/procedures/signUp';
import account_update from './resources/account/procedures/update';
import account_verifyEmail from './resources/account/procedures/verifyEmail';
import account_verifyEmailToken from './resources/account/procedures/verifyEmailToken';
import account_verifyResetToken from './resources/account/procedures/verifyResetToken';
import users_list from './resources/users/procedures/list';
import users_remove from './resources/users/procedures/remove';
import users_update from './resources/users/procedures/update';

export const router = pub.router({
  account: pub.router({ forgotPassword: account_forgotPassword, get: account_get, googleCallback: account_googleCallback, googleMobile: account_googleMobile, googleSignIn: account_googleSignIn, resendEmail: account_resendEmail, resetPassword: account_resetPassword, signIn: account_signIn, signOut: account_signOut, signUp: account_signUp, update: account_update, verifyEmail: account_verifyEmail, verifyEmailToken: account_verifyEmailToken, verifyResetToken: account_verifyResetToken }),
  users: pub.router({ list: users_list, remove: users_remove, update: users_update }),
});

export type Router = typeof router;
export type AppClient = RouterClient<Router>;
