// Auto-generated by codegen-router.ts — do not edit manually

import './resources/users/handlers/syncAnalytics';
import './resources/users/handlers/toSockets';

import type { RouterClient } from '@orpc/server';

import account_forgotPassword from './resources/account/endpoints/forgotPassword';
import account_get from './resources/account/endpoints/get';
import account_googleCallback from './resources/account/endpoints/googleCallback';
import account_googleMobile from './resources/account/endpoints/googleMobile';
import account_googleSignIn from './resources/account/endpoints/googleSignIn';
import account_resendEmail from './resources/account/endpoints/resendEmail';
import account_resetPassword from './resources/account/endpoints/resetPassword';
import account_signIn from './resources/account/endpoints/signIn';
import account_signOut from './resources/account/endpoints/signOut';
import account_signUp from './resources/account/endpoints/signUp';
import account_update from './resources/account/endpoints/update';
import account_verifyEmail from './resources/account/endpoints/verifyEmail';
import account_verifyEmailToken from './resources/account/endpoints/verifyEmailToken';
import account_verifyResetToken from './resources/account/endpoints/verifyResetToken';
import users_list from './resources/users/endpoints/list';
import users_remove from './resources/users/endpoints/remove';
import users_update from './resources/users/endpoints/update';
import { pub } from './procedures';

export const router = pub.router({
  account: pub.router({
    forgotPassword: account_forgotPassword,
    get: account_get,
    googleCallback: account_googleCallback,
    googleMobile: account_googleMobile,
    googleSignIn: account_googleSignIn,
    resendEmail: account_resendEmail,
    resetPassword: account_resetPassword,
    signIn: account_signIn,
    signOut: account_signOut,
    signUp: account_signUp,
    update: account_update,
    verifyEmail: account_verifyEmail,
    verifyEmailToken: account_verifyEmailToken,
    verifyResetToken: account_verifyResetToken,
  }),
  users: pub.router({
    list: users_list,
    remove: users_remove,
    update: users_update,
  }),
});

export type Router = typeof router;
export type AppClient = RouterClient<Router>;
