// Auto-generated by codegen-router.ts — do not edit manually

import type { RouterClient } from '@orpc/server';

import { isPublic } from './procedures';

export const router = isPublic.router({});

export type Router = typeof router;
export type AppClient = RouterClient<Router>;
