name: "Production - API Services Deploy"

on:
  push:
    branches: [ production ]
    paths:
      - 'apps/api/**'
      - 'packages/**'
      - 'deploy/app/api/**'
      - 'deploy/app/scheduler/**'
  workflow_dispatch:

jobs:
  build-api:
    uses: ./.github/workflows/build.template.yml
    secrets: inherit
    with:
      service_name: "api"
      environment: "production"
      docker_file_path: "apps/api/Dockerfile"
      helm_chart_dir: "deploy/app/api"
      cluster_name: ${{ vars.CLUSTER_NAME_PRODUCTION }}
      registry_name: ${{ vars.REGISTRY_NAME }}

  build-migrator:
    uses: ./.github/workflows/build.template.yml
    secrets: inherit
    with:
      service_name: "migrator"
      environment: "production"
      docker_file_path: "apps/api/Dockerfile.migrator"
      helm_chart_dir: "deploy/app/api"
      cluster_name: ${{ vars.CLUSTER_NAME_PRODUCTION }}
      registry_name: ${{ vars.REGISTRY_NAME }}

  build-scheduler:
    uses: ./.github/workflows/build.template.yml
    secrets: inherit
    with:
      service_name: "scheduler"
      environment: "production"
      docker_file_path: "apps/api/Dockerfile.scheduler"
      helm_chart_dir: "deploy/app/scheduler"
      cluster_name: ${{ vars.CLUSTER_NAME_PRODUCTION }}
      registry_name: ${{ vars.REGISTRY_NAME }}

  deploy-api:
    needs: [build-api, build-migrator]
    uses: ./.github/workflows/deploy.template.yml
    secrets: inherit
    with:
      service_name: "api"
      environment: "production"
      helm_chart_dir: "deploy/app/api"
      cluster_name: ${{ vars.CLUSTER_NAME_PRODUCTION }}
      node_pool: ${{ vars.CLUSTER_NODE_POOL }}
      image_tag: ${{ needs.build-api.outputs.image_tag }}
      migrator_image_tag: ${{ needs.build-migrator.outputs.image_tag }}

  deploy-scheduler:
    needs: [build-scheduler, deploy-api]
    uses: ./.github/workflows/deploy.template.yml
    secrets: inherit
    with:
      service_name: "scheduler"
      environment: "production"
      helm_chart_dir: "deploy/app/scheduler"
      cluster_name: ${{ vars.CLUSTER_NAME_PRODUCTION }}
      node_pool: ${{ vars.CLUSTER_NODE_POOL }}
      image_tag: ${{ needs.build-scheduler.outputs.image_tag }}
