FROM node:16.13.1-alpine3.13 as base
RUN apk add --no-cache python3 py3-pip

ARG NODE_ENV=development
ARG APP_ENV
ENV NODE_ENV=$NODE_ENV
ENV APP_ENV=$APP_ENV

WORKDIR /app
COPY ["./package*.json", "./tsconfig.json", "/app/"]

# Disable husky
RUN npm set-script prepare ""

RUN npm ci --quiet --include=dev
COPY . ./

RUN npm run build

FROM base as migrator
CMD npm run migrate

FROM base as scheduler
CMD npm run schedule-dev

FROM base as api
EXPOSE 3001
CMD npm run dev
