---
- name: Setup monitoring server
  hosts: monitoring
  become: true
  become_user: root
  gather_facts: False
  vars_files:
    - ["vars/main.yml"]
  roles:
    - { role: angstwad.docker_ubuntu, pip_version_docker_py: 1.9.0 }
  pre_tasks:
    - name: setup python 2 to make ansible work on ubuntu 16.04
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts
