name: "Production - Web Deploy"

on:
  push:
    branches: [ production ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'deploy/app/web/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.template.yml
    secrets: inherit
    with:
      service_name: "web"
      environment: "production"
      docker_file_path: "apps/web/Dockerfile"
      helm_chart_dir: "deploy/app/web"
      aws_access_key_id: ${{ vars.AWS_ACCESS_KEY_ID }}
      aws_region: ${{ vars.AWS_REGION }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.template.yml
    secrets: inherit
    with:
      service_name: "web"
      environment: "production"
      helm_chart_dir: "deploy/app/web"
      aws_region: ${{ vars.AWS_REGION }}
      aws_access_key_id: ${{ vars.AWS_ACCESS_KEY_ID }}
      aws_eks_name: ${{ vars.CLUSTER_NAME_PRODUCTION }}
      node_group: ${{ vars.CLUSTER_NODE_GROUP }}
      image_tag: ${{ needs.build.outputs.image_tag }}
