import { readdirSync, readFileSync, writeFileSync, existsSync, rmSync, watch } from 'node:fs';
import { join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const ROUTER_PATH = join(SRC_DIR, 'router.ts');
const HEADER = '// Auto-generated by codegen-router.ts — do not edit manually\n';

function getResources(): string[] {
  return readdirSync(RESOURCES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(RESOURCES_DIR, d.name, 'procedures')))
    .map((d) => d.name)
    .sort();
}

function getProcedures(resource: string): string[] {
  const dir = join(RESOURCES_DIR, resource, 'procedures');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
    .map((f) => basename(f, '.ts'))
    .sort();
}

function buildRouter(resources: string[]): string {
  const imports: string[] = [];
  const routerEntries: string[] = [];

  for (const r of resources) {
    const procedures = getProcedures(r);
    for (const p of procedures) {
      imports.push(`import ${r}_${p} from './resources/${r}/procedures/${p}';`);
    }
    const fields = procedures.map((p) => `${p}: ${r}_${p}`).join(', ');
    routerEntries.push(`  ${r}: pub.router({ ${fields} }),`);
  }

  return [
    HEADER,
    "import type { RouterClient } from '@orpc/server';",
    '',
    "import { pub } from './procedures';",
    '',
    ...imports,
    '',
    'export const router = pub.router({',
    ...routerEntries,
    '});',
    '',
    'export type Router = typeof router;',
    'export type AppClient = RouterClient<Router>;',
    '',
  ].join('\n');
}

function cleanBarrels(resources: string[]): void {
  for (const r of resources) {
    const barrel = join(RESOURCES_DIR, r, 'procedures', 'index.ts');
    if (existsSync(barrel)) rmSync(barrel);
  }
}

function run(): void {
  const resources = getResources();
  cleanBarrels(resources);

  const content = buildRouter(resources);
  const existing = existsSync(ROUTER_PATH) ? readFileSync(ROUTER_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(ROUTER_PATH, content);
    const total = resources.reduce((sum, r) => sum + getProcedures(r).length, 0);
    console.log(`codegen-router: ${resources.length} resources, ${total} procedures`);
  }
}

run();

if (process.argv.includes('--watch')) {
  let timeout: ReturnType<typeof setTimeout> | null = null;
  watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
    if (!filename?.endsWith('.ts')) return;
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(run, 100);
  });
}
