import { existsSync, readdirSync, readFileSync, statSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const DB_PATH = join(SRC_DIR, 'db.ts');
const HEADER = '// Auto-generated by codegen-db.ts — do not edit manually\n';

interface TableInfo {
  resource: string;
  name: string; // export name, e.g. "users"
  schemaFile: string; // e.g. "users.schema"
}

function getSchemaResources(): TableInfo[] {
  const entries = readdirSync(RESOURCES_DIR, { withFileTypes: true });
  const tables: TableInfo[] = [];

  for (const entry of entries) {
    const isDirectory =
      entry.isDirectory() || (entry.isSymbolicLink() && statSync(join(RESOURCES_DIR, entry.name)).isDirectory());
    if (!isDirectory) {
      continue;
    }

    const dir = join(RESOURCES_DIR, entry.name);
    const schemaFiles = readdirSync(dir).filter((f) => f.endsWith('.schema.ts'));

    for (const file of schemaFiles) {
      const content = readFileSync(join(dir, file), 'utf-8');

      const tableNames = new Set<string>();
      const pgTableMatches = content.matchAll(/export const (\w+)\s*=\s*pgTable\(/g);
      for (const match of pgTableMatches) {
        tableNames.add(match[1]);
        tables.push({
          resource: entry.name,
          name: match[1],
          schemaFile: basename(file, '.ts'),
        });
      }

      const aliasMatches = content.matchAll(/export const (\w+)\s*=\s*(\w+);/g);
      for (const match of aliasMatches) {
        if (tableNames.has(match[2]) && !tableNames.has(match[1])) {
          tables.push({
            resource: entry.name,
            name: match[1],
            schemaFile: basename(file, '.ts'),
          });
        }
      }
    }
  }

  return tables.sort((a, b) => a.name.localeCompare(b.name));
}

function toTypeName(tableName: string): string {
  // users -> User, tokens -> Token, blogPosts -> BlogPost
  const singular = tableName.endsWith('s') ? tableName.slice(0, -1) : tableName;
  return singular.charAt(0).toUpperCase() + singular.slice(1);
}

function buildDb(tables: TableInfo[]): string {
  const importGroups = new Map<string, Set<string>>();
  for (const t of tables) {
    const key = `@/resources/${t.resource}/${t.schemaFile}`;
    if (!importGroups.has(key)) {importGroups.set(key, new Set());}
    importGroups.get(key)!.add(t.name);
  }
  const schemaImports = [...importGroups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, names]) => `import { ${[...names].sort().join(', ')} } from '${path}';`);

  const schemaObj = tables.map((t) => `    ${t.name},`).join('\n');

  // Detect which tables have handlers/ directories → auto-hook to eventBus
  const hookedTables = new Set<string>();
  for (const t of tables) {
    const handlersDir = join(RESOURCES_DIR, t.resource, 'handlers');
    if (existsSync(handlersDir) && statSync(handlersDir).isDirectory()) {
      hookedTables.add(t.name);
    }
  }

  const hasEventBus = existsSync(join(SRC_DIR, 'event-bus.ts')) && hookedTables.size > 0;

  const createDbFields = tables.map((t) => {
    const hook = hasEventBus && hookedTables.has(t.name) ? `, eventBus.hook('${t.name}')` : '';
    return `  ${t.name}: new DbService(${t.name}, db${hook}),`;
  });

  const dbTypeFields = tables.map((t) => `  ${t.name}: DbService<typeof ${t.name}>;`);

  const typeExports = tables.map((t) => `export type ${toTypeName(t.name)} = typeof ${t.name}.$inferSelect;`);

  const hasRelations = existsSync(join(SRC_DIR, 'relations.ts'));

  return [
    HEADER,
    "import _db, { DbService, registerDb } from '@ship/db';",
    "import { drizzle } from 'drizzle-orm/postgres-js';",
    "import postgres from 'postgres';",
    '',
    "import config from '@/config';",
    ...(hasEventBus ? ["import { eventBus } from '@/event-bus';"] : []),
    ...(hasRelations ? ["import { relations } from '@/relations';"] : []),
    ...schemaImports,
    '',
    'const client = postgres(config.DATABASE_URL);',
    '',
    'export const rawDb = drizzle({',
    '  client,',
    "  casing: 'snake_case',",
    '  schema: {',
    schemaObj,
    '  },',
    ...(hasRelations ? ['  relations,'] : []),
    '});',
    '',
    'const createDB = (db: typeof rawDb) => ({',
    ...createDbFields,
    '  transaction: getTransactionalDB,',
    '});',
    '',
    'type TransactionCallback<T> = (db: DBType) => Promise<T>;',
    '',
    'function getTransactionalDB<T>(callback: TransactionCallback<T>): Promise<T> {',
    '  return rawDb.transaction(async (tx) => {',
    '    // eslint-disable-next-line ts/no-explicit-any',
    '    return await callback(createDB(tx as any));',
    '  });',
    '}',
    '',
    'registerDb(createDB(rawDb), rawDb);',
    '',
    'interface DBType {',
    ...dbTypeFields,
    '  transaction: <T>(callback: TransactionCallback<T>) => Promise<T>;',
    '}',
    '',
    '// eslint-disable-next-line ts/no-explicit-any',
    'export default _db as any as DBType;',
    '',
    ...typeExports,
    '',
  ].join('\n');
}

function run(): void {
  const tables = getSchemaResources();
  const content = buildDb(tables);
  const existing = existsSync(DB_PATH) ? readFileSync(DB_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(DB_PATH, content);
    // eslint-disable-next-line no-console
    console.log(`codegen-db: ${tables.length} tables (${tables.map((t) => t.name).join(', ')})`);
  }
}

run();

if (process.argv.includes('--watch')) {
  let timeout: ReturnType<typeof setTimeout> | null = null;
  watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
    if (!filename?.endsWith('.schema.ts')) {
      return;
    }
    if (timeout) {
      clearTimeout(timeout);
    }
    timeout = setTimeout(run, 100);
  });
}
