import { existsSync, readdirSync, readFileSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname,join  } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const OUTPUT_PATH = join(SRC_DIR, 'db.ts');
const HEADER = '// Auto-generated by codegen-db-types.ts — do not edit manually\n';

interface SchemaEntry {
  name: string;
  resourceDir: string;
}

function discoverSchemas(): SchemaEntry[] {
  const schemas: SchemaEntry[] = [];
  const entries = readdirSync(RESOURCES_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const dirPath = join(RESOURCES_DIR, entry.name);
    const files = readdirSync(dirPath);
    const schemaFiles = files.filter((f) => f.endsWith('.schema.ts') || f.endsWith('.schema.js'));

    for (const schemaFile of schemaFiles) {
      const name = basename(schemaFile).replace(/\.schema\.(ts|js)$/, '');
      schemas.push({ name, resourceDir: entry.name });
    }
  }

  return schemas;
}

export function run(): void {
  const schemas = discoverSchemas();

  const imports = schemas.map(
    (s) => `import type ${s.name}Schema from 'resources/${s.resourceDir}/${s.name}.schema';`,
  );

  const serviceExports = schemas.map(
    (s) => `export const ${s.name}Service = services.${s.name} as Service<z.infer<typeof ${s.name}Schema>>;`,
  );

  const content = [
    HEADER,
    "import type { z } from 'zod';",
    "import type { Service } from '@paralect/node-mongo';",
    ...imports,
    "import { services } from 'initDb';",
    '',
    ...serviceExports,
    '',
  ].join('\n');

  const existing = existsSync(OUTPUT_PATH) ? readFileSync(OUTPUT_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(OUTPUT_PATH, content);
    // eslint-disable-next-line no-console
    console.log(`codegen-db-types: ${schemas.length} schemas`);
  }
}

run();

if (process.argv.includes('--watch')) {
  let timeout: ReturnType<typeof setTimeout> | null = null;
  watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
    if (!filename?.includes('.schema.')) return;
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(run, 100);
  });
}
