import { existsSync, readdirSync, readFileSync, statSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const ROUTER_PATH = join(SRC_DIR, 'router.ts');
const CONTRACT_PATH = join(SRC_DIR, 'contract.ts');
const RESOURCE_CLIENT_PATH = join(SRC_DIR, 'resource-client.ts');
const HEADER = '// Auto-generated by codegen-router.ts — do not edit manually\n';

// ---------------------------------------------------------------------------
// Filesystem-based routing conventions:
//   CRUD files:  list.ts → GET (collection), create.ts → POST (collection),
//                get.ts → GET, update.ts → PUT, delete.ts → DELETE
//   Method-suffixed:  name.post.ts → POST /name, status.get.ts → GET /status
//   [param] folders:  [groupId]/ → {groupId} dynamic segment
//   Escape hatch:  if file has .route({ method, path }), that overrides
// ---------------------------------------------------------------------------

const CRUD_MAP: Record<string, string> = {
  list: 'GET',
  create: 'POST',
  get: 'GET',
  update: 'PUT',
  delete: 'DELETE',
};

const VALID_METHODS = new Set(['GET', 'POST', 'PUT', 'PATCH', 'DELETE']);

function toCamelCase(str: string): string {
  return str.replace(/[-/_]([a-z])/g, (_, c: string) => c.toUpperCase());
}

function stripMethodSuffix(fileName: string): { name: string; hasMethodSuffix: boolean } {
  const dotParts = fileName.split('.');
  if (dotParts.length >= 2 && VALID_METHODS.has(dotParts[dotParts.length - 1].toUpperCase())) {
    return { name: dotParts.slice(0, -1).join('.'), hasMethodSuffix: true };
  }
  return { name: fileName, hasMethodSuffix: false };
}

function buildRouterKey(relPath: string): string {
  const parts = relPath.split('/');
  const fileName = parts[parts.length - 1];
  const dirParts = parts.slice(0, -1);

  // Keep non-param dirs for context (e.g., bank-accounts/ → bankAccounts)
  const nonParamDirs = dirParts.filter((p) => !p.startsWith('['));

  // Strip method suffix from file name
  const { name } = stripMethodSuffix(fileName);

  // Combine context dirs + name
  const keyParts = [...nonParamDirs, name];
  return toCamelCase(keyParts.join('-'));
}

function buildImportId(resourcePath: string, relPath: string): string {
  const parts = relPath.split('/');
  const fileName = parts[parts.length - 1];
  const dirParts = parts.slice(0, -1);

  // Strip brackets from param dirs
  const cleanDirs = dirParts.map((p) => p.replace(/[[\]]/g, ''));

  // Strip method suffix
  const { name } = stripMethodSuffix(fileName);

  // Combine resource + dirs + name
  const combined = [resourcePath, ...cleanDirs, name].join('_');
  return toCamelCase(combined);
}

function quoteKey(key: string): string {
  return key.includes('-') ? `'${key}'` : key;
}

// ---------------------------------------------------------------------------
// Endpoint scanning — recursively walk endpoints/ (supports [param] folders)
// ---------------------------------------------------------------------------

interface EndpointEntry {
  relPath: string;
  absPath: string;
  method: string;
  httpPath: string;
  importId: string;
  importFrom: string;
  routerKey: string;
  extraRouteProps: Record<string, string | number>;
}

function scanEndpointsDir(dir: string, segments: string[] = []): { relPath: string; absPath: string }[] {
  const entries: { relPath: string; absPath: string }[] = [];
  if (!existsSync(dir)) {
    return entries;
  }

  const items = readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));

  for (const item of items) {
    if (item.isDirectory()) {
      entries.push(...scanEndpointsDir(join(dir, item.name), [...segments, item.name]));
    } else if (item.isFile() && item.name.endsWith('.ts') && item.name !== 'index.ts') {
      const fullName = basename(item.name, '.ts');
      entries.push({
        relPath: [...segments, fullName].join('/'),
        absPath: join(dir, item.name),
      });
    }
  }

  return entries;
}

function deriveMethodAndPathSegments(relPath: string): { method: string; pathSegments: string[] } {
  const parts = relPath.split('/');
  const fileName = parts[parts.length - 1];
  const dirParts = parts.slice(0, -1);

  // Convert [param] folders to {param}
  const pathParts = dirParts.map((p) => (p.startsWith('[') && p.endsWith(']') ? `{${p.slice(1, -1)}}` : p));

  // Parse file name
  const dotParts = fileName.split('.');
  if (dotParts.length >= 2 && VALID_METHODS.has(dotParts[dotParts.length - 1].toUpperCase())) {
    const method = dotParts.pop()!.toUpperCase();
    const name = dotParts.join('.');
    return { method, pathSegments: [...pathParts, name] };
  }

  if (CRUD_MAP[fileName]) {
    return { method: CRUD_MAP[fileName], pathSegments: pathParts };
  }

  // Fallback — unknown convention, will rely on explicit .route()
  return { method: '', pathSegments: [...pathParts, fileName] };
}

function parseExplicitRoute(absPath: string): {
  method?: string;
  path?: string;
  extraProps: Record<string, string | number>;
} {
  const content = readFileSync(absPath, 'utf-8');
  const routeMatch = content.match(/\.route\(\s*\{([\s\S]*?)\}\s*\)/);
  if (!routeMatch) {
    return { extraProps: {} };
  }

  const body = routeMatch[1];
  const methodMatch = body.match(/method:\s*['"](\w+)['"]/);
  const pathMatch = body.match(/path:\s*['"]([^'"]+)['"]/);

  const extraProps: Record<string, string | number> = {};
  const statusMatch = body.match(/successStatus:\s*(\d+)/);
  if (statusMatch) {
    extraProps.successStatus = Number.parseInt(statusMatch[1]);
  }
  const structureMatch = body.match(/outputStructure:\s*['"](\w+)['"]/);
  if (structureMatch) {
    extraProps.outputStructure = structureMatch[1];
  }

  return {
    method: methodMatch?.[1],
    path: pathMatch?.[1],
    extraProps,
  };
}

// ---------------------------------------------------------------------------
// Resource discovery
// ---------------------------------------------------------------------------

interface ResourceInfo {
  path: string;
  endpoints: EndpointEntry[];
  handlers: string[];
}

// eslint-disable-next-line ts/no-explicit-any
function isDir(entry: any, parentDir: string): boolean {
  return entry.isDirectory() || (entry.isSymbolicLink() && statSync(join(parentDir, entry.name)).isDirectory());
}

function discoverResources(): ResourceInfo[] {
  if (!existsSync(RESOURCES_DIR)) {
    return [];
  }
  const resources: ResourceInfo[] = [];

  function scan(dir: string, resourcePath: string): void {
    if (existsSync(join(dir, 'endpoints'))) {
      const rawEntries = scanEndpointsDir(join(dir, 'endpoints'));
      const resourceSegments = resourcePath.split('/');

      const endpoints: EndpointEntry[] = rawEntries.map((raw) => {
        const derived = deriveMethodAndPathSegments(raw.relPath);
        const explicit = parseExplicitRoute(raw.absPath);

        const method = explicit.method || derived.method || 'POST';
        const httpPath = explicit.path || `/${[...resourceSegments, ...derived.pathSegments].join('/')}`;

        const importId = buildImportId(resourcePath, raw.relPath);
        const importFrom = `./resources/${resourcePath}/endpoints/${raw.relPath}`;
        const routerKey = buildRouterKey(raw.relPath);

        return {
          relPath: raw.relPath,
          absPath: raw.absPath,
          method,
          httpPath,
          importId,
          importFrom,
          routerKey,
          extraRouteProps: explicit.extraProps,
        };
      });

      // Resolve duplicate router keys by prepending method
      const keyCounts = new Map<string, number>();
      for (const ep of endpoints) {
        keyCounts.set(ep.routerKey, (keyCounts.get(ep.routerKey) || 0) + 1);
      }
      for (const ep of endpoints) {
        if (keyCounts.get(ep.routerKey)! > 1) {
          const methodPrefix = ep.method.toLowerCase();
          ep.routerKey = toCamelCase(`${methodPrefix}-${ep.routerKey}`);
          ep.importId = toCamelCase(`${ep.importId}-${methodPrefix}`);
        }
      }

      // Handlers
      const handlersDir = join(dir, 'handlers');
      const handlers: string[] = [];
      if (existsSync(handlersDir)) {
        for (const f of readdirSync(handlersDir).sort()) {
          if (f.endsWith('.ts')) {
            handlers.push(basename(f, '.ts'));
          }
        }
      }

      resources.push({ path: resourcePath, endpoints, handlers });
    }

    // Scan subdirectories for nested resources (e.g. stripe/connect)
    for (const sub of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (sub.name === 'endpoints' || sub.name === 'handlers') {
        continue;
      }
      if (!isDir(sub, dir)) {
        continue;
      }
      scan(join(dir, sub.name), resourcePath ? `${resourcePath}/${sub.name}` : sub.name);
    }
  }

  for (const d of readdirSync(RESOURCES_DIR, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (!isDir(d, RESOURCES_DIR)) {
      continue;
    }
    scan(join(RESOURCES_DIR, d.name), d.name);
  }

  return resources.sort((a, b) => a.path.localeCompare(b.path));
}

// ---------------------------------------------------------------------------
// Nested router tree
// ---------------------------------------------------------------------------

interface RouterNode {
  key: string;
  endpoints: EndpointEntry[];
  children: RouterNode[];
}

/** Extract leading non-param dirs from relPath as nesting levels. */
function splitNonParamPrefix(relPath: string): { nestingDirs: string[]; leafRelPath: string } {
  const parts = relPath.split('/');
  const nestingDirs: string[] = [];
  for (let i = 0; i < parts.length - 1; i++) {
    if (!parts[i].startsWith('[')) {
      nestingDirs.push(parts[i]);
    } else {
      break;
    }
  }
  return { nestingDirs, leafRelPath: parts.slice(nestingDirs.length).join('/') };
}

/** Resolve duplicate routerKeys within a node by prepending HTTP method. */
function deduplicateNodeKeys(node: RouterNode): void {
  const keyCounts = new Map<string, number>();
  for (const ep of node.endpoints) {
    keyCounts.set(ep.routerKey, (keyCounts.get(ep.routerKey) || 0) + 1);
  }
  for (const ep of node.endpoints) {
    if (keyCounts.get(ep.routerKey)! > 1) {
      ep.routerKey = toCamelCase(`${ep.method.toLowerCase()}-${ep.routerKey}`);
    }
  }
  for (const child of node.children) {
    deduplicateNodeKeys(child);
  }
}

function buildTree(resources: ResourceInfo[]): RouterNode[] {
  const root: RouterNode[] = [];

  for (const r of resources) {
    const parts = r.path.split('/');
    let siblings = root;

    for (let i = 0; i < parts.length; i++) {
      const key = parts[i];
      let node = siblings.find((n) => n.key === key);
      if (!node) {
        node = { key, endpoints: [], children: [] };
        siblings.push(node);
      }
      if (i === parts.length - 1) {
        // Distribute endpoints: non-param dir prefixes in relPath become nested nodes
        for (const ep of r.endpoints) {
          const { nestingDirs, leafRelPath } = splitNonParamPrefix(ep.relPath);
          let target = node;
          for (const dir of nestingDirs) {
            const childKey = toCamelCase(dir);
            let child = target.children.find((n) => n.key === childKey);
            if (!child) {
              child = { key: childKey, endpoints: [], children: [] };
              target.children.push(child);
            }
            target = child;
          }
          target.endpoints.push({ ...ep, routerKey: buildRouterKey(leafRelPath) });
        }
      }
      siblings = node.children;
    }
  }

  for (const node of root) {
    deduplicateNodeKeys(node);
  }

  return root;
}

// ---------------------------------------------------------------------------
// Router codegen
// ---------------------------------------------------------------------------

function renderRouterNode(node: RouterNode, indent: number): string {
  const innerPad = ' '.repeat(indent + 2);
  const fields: string[] = [];

  for (const ep of node.endpoints) {
    fields.push(`${innerPad}${toCamelCase(ep.routerKey)}: ${ep.importId},`);
  }

  for (const child of node.children.sort((a, b) => a.key.localeCompare(b.key))) {
    const childContent = renderRouterNode(child, indent + 2);
    fields.push(`${innerPad}${quoteKey(child.key)}: {\n${childContent}\n${innerPad}},`);
  }

  return fields.join('\n');
}

function buildRouter(resources: ResourceInfo[]): string {
  const tree = buildTree(resources);
  const handlerImports: string[] = [];
  const imports: string[] = [];

  for (const r of resources) {
    for (const h of r.handlers) {
      handlerImports.push(`import './resources/${r.path}/handlers/${h}';`);
    }
    for (const ep of r.endpoints) {
      imports.push(`import ${ep.importId} from '${ep.importFrom}';`);
    }
  }

  const routerEntries: string[] = [];
  for (const node of tree.sort((a, b) => a.key.localeCompare(b.key))) {
    const content = renderRouterNode(node, 2);
    routerEntries.push(`  ${quoteKey(node.key)}: {\n${content}\n  },`);
  }

  return [
    HEADER,
    ...handlerImports,
    ...(handlerImports.length ? [''] : []),
    "import type { RouterClient } from '@orpc/server';",
    "import { implement } from '@orpc/server';",
    '',
    ...imports,
    "import { contract } from './contract';",
    "import type { ORPCContext } from './types';",
    '',
    'export const router = implement(contract).$context<ORPCContext>().router({',
    ...routerEntries,
    '});',
    '',
    'export type Router = typeof router;',
    'export type AppClient = RouterClient<Router>;',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Contract codegen
// ---------------------------------------------------------------------------

function renderContractNode(node: RouterNode, indent: number): string {
  const innerPad = ' '.repeat(indent + 2);
  const fields: string[] = [];

  for (const ep of node.endpoints) {
    const props = [`method: '${ep.method}'`, `path: '${ep.httpPath}'`];
    if (ep.extraRouteProps.successStatus) {
      props.push(`successStatus: ${ep.extraRouteProps.successStatus}`);
    }
    if (ep.extraRouteProps.outputStructure) {
      props.push(`outputStructure: '${ep.extraRouteProps.outputStructure}'`);
    }
    fields.push(`${innerPad}${toCamelCase(ep.routerKey)}: oc.route({ ${props.join(', ')} }),`);
  }

  for (const child of node.children.sort((a, b) => a.key.localeCompare(b.key))) {
    const childContent = renderContractNode(child, indent + 2);
    fields.push(`${innerPad}${quoteKey(child.key)}: oc.router({\n${childContent}\n${innerPad}}),`);
  }

  return fields.join('\n');
}

function buildContract(resources: ResourceInfo[]): string {
  const tree = buildTree(resources);

  const contractEntries: string[] = [];
  for (const node of tree.sort((a, b) => a.key.localeCompare(b.key))) {
    const content = renderContractNode(node, 2);
    contractEntries.push(`  ${quoteKey(node.key)}: oc.router({\n${content}\n  }),`);
  }

  return [
    HEADER,
    "import { oc } from '@orpc/contract';",
    '',
    'export const contract = oc.router({',
    ...contractEntries,
    '});',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Resource client codegen
// ---------------------------------------------------------------------------

function extractParams(httpPath: string): string[] {
  return [...httpPath.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
}

function clientIdx(key: string): string {
  return `['${key}']`;
}

function buildResourceClient(resources: ResourceInfo[]): string {
  const tree = buildTree(resources);
  const L: string[] = [];

  L.push(HEADER);
  L.push("import type { AppClient } from './router';");
  L.push('');
  L.push('// eslint-disable-next-line ts/no-explicit-any');
  L.push('type AnyFn = (...args: any[]) => any;');
  L.push('');
  L.push('type _BindInput<T extends AnyFn, K extends string> =');
  L.push('  T extends (input: infer I, ...rest: infer R) => infer O');
  L.push('    ? keyof Omit<I & {}, K> extends never');
  L.push('      ? (...rest: R) => O');
  L.push('      : (input: Omit<I & {}, K>, ...rest: R) => O');
  L.push('    : T;');
  L.push('');

  for (const node of tree.sort((a, b) => a.key.localeCompare(b.key))) {
    const base = clientIdx(node.key);
    const name = `${toCamelCase(node.key).charAt(0).toUpperCase() + toCamelCase(node.key).slice(1)}Resource`;
    const paramEps: EndpointEntry[] = [];
    const plainEps: EndpointEntry[] = [];
    const paramSet = new Set<string>();

    for (const ep of node.endpoints) {
      const p = extractParams(ep.httpPath);
      if (p.length > 0) {
        paramEps.push(ep);
        p.forEach((x) => paramSet.add(x));
      } else {
        plainEps.push(ep);
      }
    }

    if (paramSet.size === 0 && node.children.length === 0) {
      L.push(`export type ${name} = AppClient${base};`);
      L.push('');
      continue;
    }

    if (paramSet.size === 0) {
      L.push(`export type ${name} = AppClient${base};`);
      L.push('');
      continue;
    }

    const params = [...paramSet];
    const paramType = `{ ${params.map((p) => `${p}: string`).join('; ')} }`;
    const paramUnion = params.map((p) => `'${p}'`).join(' | ');

    L.push(`export interface ${name} {`);
    L.push(`  (params: ${paramType}): {`);
    for (const ep of paramEps) {
      const k = toCamelCase(ep.routerKey);
      L.push(`    ${k}: _BindInput<AppClient${base}${clientIdx(k)}, ${paramUnion}>;`);
    }
    L.push('  };');
    for (const ep of plainEps) {
      const k = toCamelCase(ep.routerKey);
      L.push(`  ${k}: AppClient${base}${clientIdx(k)};`);
    }
    for (const child of node.children.sort((a, b) => a.key.localeCompare(b.key))) {
      L.push(`  ${quoteKey(child.key)}: AppClient${base}${clientIdx(child.key)};`);
    }
    L.push('}');
    L.push('');
  }

  L.push('export interface ResourceClient {');
  for (const node of tree.sort((a, b) => a.key.localeCompare(b.key))) {
    const name = `${toCamelCase(node.key).charAt(0).toUpperCase() + toCamelCase(node.key).slice(1)}Resource`;
    L.push(`  ${quoteKey(node.key)}: ${name};`);
  }
  L.push('}');
  L.push('');

  return L.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function run(): void {
  const resources = discoverResources();

  const content = buildRouter(resources);
  const existing = existsSync(ROUTER_PATH) ? readFileSync(ROUTER_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(ROUTER_PATH, content);
    const total = resources.reduce((sum, r) => sum + r.endpoints.length, 0);
    // eslint-disable-next-line no-console
    console.log(`codegen-router: ${resources.length} resources, ${total} endpoints`);
  }

  const contractContent = buildContract(resources);
  const existingContract = existsSync(CONTRACT_PATH) ? readFileSync(CONTRACT_PATH, 'utf-8') : '';

  if (contractContent !== existingContract) {
    writeFileSync(CONTRACT_PATH, contractContent);
  }

  const rcContent = buildResourceClient(resources);
  const existingRc = existsSync(RESOURCE_CLIENT_PATH) ? readFileSync(RESOURCE_CLIENT_PATH, 'utf-8') : '';
  if (rcContent !== existingRc) {
    writeFileSync(RESOURCE_CLIENT_PATH, rcContent);
  }
}

run();

if (process.argv.includes('--watch')) {
  if (existsSync(RESOURCES_DIR)) {
    let timeout: ReturnType<typeof setTimeout> | null = null;
    watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
      if (!filename?.endsWith('.ts')) {
        return;
      }
      if (timeout) {
        clearTimeout(timeout);
      }
      timeout = setTimeout(run, 100);
    });
  }
}
