import { existsSync, readdirSync, readFileSync, rmSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const ROUTER_PATH = join(SRC_DIR, 'router.ts');
const HEADER = '// Auto-generated by codegen-router.ts — do not edit manually\n';

function getResources(): string[] {
  return readdirSync(RESOURCES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(RESOURCES_DIR, d.name, 'endpoints')))
    .map((d) => d.name)
    .sort();
}

function getEndpoints(resource: string): string[] {
  const dir = join(RESOURCES_DIR, resource, 'endpoints');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
    .map((f) => basename(f, '.ts'))
    .sort();
}

function getHandlers(resource: string): string[] {
  const dir = join(RESOURCES_DIR, resource, 'handlers');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => basename(f, '.ts'))
    .sort();
}

function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function buildRouter(resources: string[]): string {
  const handlerImports: string[] = [];
  const imports: string[] = [];
  const routerEntries: string[] = [];

  for (const r of resources) {
    for (const h of getHandlers(r)) {
      handlerImports.push(`import './resources/${r}/handlers/${h}';`);
    }

    const endpoints = getEndpoints(r);
    for (const p of endpoints) {
      const id = toCamelCase(`${r}_${p}`);
      imports.push(`import ${id} from './resources/${r}/endpoints/${p}';`);
    }
    const fields = endpoints.map((p) => `    ${toCamelCase(p)}: ${toCamelCase(`${r}_${p}`)},`);
    routerEntries.push(`  ${r}: pub.router({\n${fields.join('\n')}\n  }),`);
  }

  return [
    HEADER,
    ...handlerImports,
    ...(handlerImports.length ? [''] : []),
    "import type { RouterClient } from '@orpc/server';",
    '',
    ...imports,
    "import { pub } from './procedures';",
    '',
    'export const router = pub.router({',
    ...routerEntries,
    '});',
    '',
    'export type Router = typeof router;',
    'export type AppClient = RouterClient<Router>;',
    '',
  ].join('\n');
}

function cleanBarrels(resources: string[]): void {
  for (const r of resources) {
    const barrel = join(RESOURCES_DIR, r, 'endpoints', 'index.ts');
    if (existsSync(barrel)) rmSync(barrel);
  }
}

function run(): void {
  const resources = getResources();
  cleanBarrels(resources);

  const content = buildRouter(resources);
  const existing = existsSync(ROUTER_PATH) ? readFileSync(ROUTER_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(ROUTER_PATH, content);
    const total = resources.reduce((sum, r) => sum + getEndpoints(r).length, 0);
    // eslint-disable-next-line no-console
    console.log(`codegen-router: ${resources.length} resources, ${total} endpoints`);
  }
}

run();

if (process.argv.includes('--watch')) {
  let timeout: ReturnType<typeof setTimeout> | null = null;
  watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
    if (!filename?.endsWith('.ts')) return;
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(run, 100);
  });
}
