import { existsSync, readdirSync, readFileSync, statSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');
const RESOURCES_DIR = join(SRC_DIR, 'resources');
const DB_PATH = join(SRC_DIR, 'db.ts');
const HEADER = '// Auto-generated by codegen-db.ts — do not edit manually\n';

interface TableInfo {
  resource: string;
  name: string; // export name, e.g. "users"
  schemaFile: string; // e.g. "users.schema"
}

function getSchemaResources(): TableInfo[] {
  const entries = readdirSync(RESOURCES_DIR, { withFileTypes: true });
  const tables: TableInfo[] = [];

  for (const entry of entries) {
    const isDirectory =
      entry.isDirectory() || (entry.isSymbolicLink() && statSync(join(RESOURCES_DIR, entry.name)).isDirectory());
    if (!isDirectory) {
      continue;
    }

    const dir = join(RESOURCES_DIR, entry.name);
    const schemaFiles = readdirSync(dir).filter((f) => f.endsWith('.schema.ts'));

    for (const file of schemaFiles) {
      const content = readFileSync(join(dir, file), 'utf-8');
      const matches = content.matchAll(/export const (\w+)\s*=\s*pgTable\(/g);

      for (const match of matches) {
        tables.push({
          resource: entry.name,
          name: match[1],
          schemaFile: basename(file, '.ts'),
        });
      }
    }
  }

  return tables.sort((a, b) => a.name.localeCompare(b.name));
}

function toTypeName(tableName: string): string {
  // users -> User, tokens -> Token, blogPosts -> BlogPost
  const singular = tableName.endsWith('s') ? tableName.slice(0, -1) : tableName;
  return singular.charAt(0).toUpperCase() + singular.slice(1);
}

function buildDb(tables: TableInfo[]): string {
  const schemaImports = tables.map((t) => `import { ${t.name} } from '@/resources/${t.resource}/${t.schemaFile}';`);

  const schemaObj = tables.map((t) => t.name).join(', ');
  const dbFields = tables.map((t) => `  ${t.name}: new DbService(${t.name}, rawDb),`);
  const typeExports = tables.map((t) => `export type ${toTypeName(t.name)} = typeof ${t.name}.$inferSelect;`);

  return [
    HEADER,
    "import { drizzle } from 'drizzle-orm/postgres-js';",
    "import postgres from 'postgres';",
    '',
    "import config from '@/config';",
    "import { DbService, registerDb } from '@ship/db';",
    ...schemaImports,
    '',
    'const client = postgres(config.DATABASE_URL);',
    '',
    `const rawDb = drizzle({ client, schema: { ${schemaObj} } });`,
    '',
    `registerDb({`,
    ...dbFields,
    '}, rawDb);',
    '',
    "export { default } from '@ship/db';",
    '',
    ...typeExports,
    '',
  ].join('\n');
}

function run(): void {
  const tables = getSchemaResources();
  const content = buildDb(tables);
  const existing = existsSync(DB_PATH) ? readFileSync(DB_PATH, 'utf-8') : '';

  if (content !== existing) {
    writeFileSync(DB_PATH, content);
    // eslint-disable-next-line no-console
    console.log(`codegen-db: ${tables.length} tables (${tables.map((t) => t.name).join(', ')})`);
  }
}

run();

if (process.argv.includes('--watch')) {
  let timeout: ReturnType<typeof setTimeout> | null = null;
  watch(RESOURCES_DIR, { recursive: true }, (_, filename) => {
    if (!filename?.endsWith('.schema.ts')) {
      return;
    }
    if (timeout) {
      clearTimeout(timeout);
    }
    timeout = setTimeout(run, 100);
  });
}
