name: 'Application api deployment'

on:
  push:
    branches: [ main ]
    paths:
      - 'template/apps/api/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Update DigitalOcean App Platform
        run: doctl apps create-deployment ${{ secrets.DO_APP_API_ID }} --wait
